apps/desktop/src/components/toast/model.tsx, apps/desktop/src/routes/app.tsx
=> Fix: Prevent onboarding modal re-render from retriggering model download toast

apps/desktop/src/contexts/right-panel.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po, plugins/windows/src/ext.rs
This is to let people know the existence of the right panel button, located on the top-right corner. 
They can close it if they want to, once they learn about it.
=> Show right panel as default

apps/desktop/src/components/editor-area/floating-button.tsx, packages/ui/src/components/ui/splash.tsx
- Refactored splash component and updated floating button with a new loader animation.
- Replaced RotateCcw icon with RefreshCw icon and added a fade transition between icons.
- Cleaned up code formatting in `splash.tsx` and `floating-button.tsx` for improved readability and maintainability.
=> Refactor Splash UI and Floating Button with New Loader Animation and Icon Transition

apps/desktop/src/components/left-sidebar/top-area/settings-button.tsx, apps/desktop/src/components/settings/components/main-sidebar.tsx, apps/desktop/src/components/settings/components/tab-icon.tsx, apps/desktop/src/components/settings/components/types.ts, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po, apps/desktop/src/routes/app.settings.tsx, apps/docs/data/i18n.json
Refactored settings sidebar and tab rendering logic for improved readability and maintainability.
Removed unused Profile tab and related icon imports from settings components.
Simplified MainSidebar tab label rendering and JSX structure.
Cleaned up app.settings.tsx imports and conditional rendering with concise syntax.
Replaced SettingsButton tooltip with a dropdown menu, adding a "My Profile" item linked to the current user.
Updated icons in SettingsButton for better UX and accessibility.
Added new translation keys for "Settings," "My Profile," and "Local mode" in Korean and English locales.
=> Refactor Settings UI and Sidebar Logic with Cleanup, UX Improvements, and i18n Updates

apps/desktop/src/components/organization-profile/members-list.tsx, apps/desktop/src/components/organization-profile/recent-notes.tsx, apps/desktop/src/components/organization-profile/upcoming-events.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po, apps/desktop/src/routes/app.organization.$id.tsx
- Improved the organization edit form UI, including a centered building icon and organization name, a more compact and organized layout, and an optional description field
- Added an auto-resizing textarea for the organization description field
- Enhanced the members list UI by displaying member profiles in a table format with additional information
- Centered the recent notes section and limited its width for a more visually appealing layout
- Centered the "Upcoming Events" title and limited the event cards to a max width for better readability and consistency
- Added internationalization (i18n) support
=> Improve Organization Page UI and Add i18n Support

apps/desktop/src/components/editor-area/note-header/listen-button.tsx
Refactor the `ListenButton` component to enhance its appearance and
functionality. The main changes include:
- Replace `clsx` with `cn` utility for more concise class name
management.
- Improve the button styles, including hover effects and disabled
states.
- Optimize the logic for handling ongoing session status changes to
provide a better user experience.
=> feat(listen-button): Improve button styles and functionality

crates/db-user/assets/onboarding-raw.html
Adds an example blockquote for user notes and enhances the note
display by adding a new line between the note and the local
privacy/offline text.
=> feat(onboarding): Add example notes and enhance note display

apps/desktop/src/components/editor-area/note-header/listen-button.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po
- Improved the behavior of the listen button in the note header component
- Simplified the button's disabled state and hover behavior
- Added a "Wait..." text to the button when it is disabled
- Updated the text displayed on the listen button to better reflect its state
=> Refactor Listen Button Behavior and Text in Note Header

Cargo.lock, apps/desktop/src/components/settings/views/lab.tsx, crates/detect/src/macos.rs, crates/notification2/src/lib.rs, crates/notification2/src/macos.rs, plugins/notification/src/lib.rs
Fix various issues I missed in #256.
=> Fix notification plugin

apps/desktop/src/components/right-panel/components/widget-renderer/index.tsx
Adds a bottom margin to the widget container and fixes an issue where the "Edit Widgets" button was not properly aligned with the widgets. These changes improve the overall layout and appearance of the widget section in the right panel.
=> Improve widget layout and add margin

crates/db-user/src/init.rs
- Add sample session data with event linking to the `db-user` crate
- Include sessions linked to specific calendar events (Daily Standup, Project Kickoff)
- Add sessions with various creation/visit timestamps to test sorting and grouping
- Include sessions with different levels of detail in the memo content
- Add an untitled session to test handling of sessions without a title
- Provide a more realistic set of sample data to aid in the development and testing of the notes feature
=> Add sample session data with event linking

apps/desktop/src/routes/app.plans.tsx, packages/ui/src/components/ui/progressive-blur.tsx, plugins/windows/src/ext.rs
- Implemented a new `ProgressiveBlur` component that applies a progressive blur effect to its children using a series of overlapping gradient masks and backdrop filters
- Updated the pricing card details on the plans page:
- Removed the "price" prop from the `PricingCard` component
- Simplified the "Local" plan features and updated the "Pro" plan features
- Replaced the "Pro" plan button with a link to the waitlist
- Adjusted the button styles for a consistent user experience
- Adjusted the default size of the Plans window to 900x600 pixels to ensure the content is fully visible without scrolling
=> Add ProgressiveBlur Component and Update Plans Page UI and Layout

apps/desktop/src-tauri/tauri.conf.json
Increased window height from 400 to 430 pixels to provide more space for application content and improve user experience
=> Update DMG window size

.cargo/config.toml, CONTRIBUTING.md
I was trying to build it and ran across some errors that were due to architecture confusion in the build process. I wrote up the changes I made locally so that others would have an easier time building it themselves!
Thank you to @yujonglee for the help in debugging the issue!
=> Updated build instructions + Small `config.toml` fix

Cargo.lock, Cargo.toml, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/lib.rs, extensions/transcript/package.json, extensions/transcript/src/widgets/default/2x2.tsx, extensions/transcript/src/widgets/default/full.tsx, plugins/misc/Cargo.toml, plugins/misc/build.rs, plugins/misc/js/bindings.gen.ts, plugins/misc/permissions/autogenerated/commands/open_audio.toml, plugins/misc/permissions/autogenerated/reference.md, plugins/misc/permissions/default.toml, plugins/misc/permissions/schemas/schema.json, plugins/misc/src/commands.rs, plugins/misc/src/lib.rs, pnpm-lock.yaml
=> Add audio opener

packages/utils/src/stores/sessions.ts
=> Update session state in store

apps/desktop/src/components/editor-area/note-header/listen-button.tsx, apps/desktop/src/components/left-sidebar/index.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po
Added loading state to the listen button to improve user experience
=> Add Loading State for Listen Button

Cargo.lock, apps/desktop/src-tauri/src/ext.rs, apps/desktop/src/components/editor-area/index.tsx, apps/desktop/src/components/toast/shared.tsx, packages/utils/src/ai.ts, plugins/connector/Cargo.toml, plugins/connector/src/error.rs, plugins/connector/src/ext.rs, plugins/connector/src/lib.rs, plugins/connector/src/types.rs, plugins/local-llm/src/error.rs, plugins/local-llm/src/ext.rs, plugins/local-stt/src/commands.rs, plugins/local-stt/src/error.rs, plugins/local-stt/src/ext.rs
=> Handle invalid LLM connection

apps/desktop/src/components/settings/views/ai.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po, apps/docs/data/i18n.json, crates/buffer/src/lib.rs, packages/utils/package.json, packages/utils/src/ai.ts, plugins/connector/build.rs, plugins/connector/js/bindings.gen.ts, plugins/connector/permissions/autogenerated/commands/get_custom_llm_model.toml, plugins/connector/permissions/autogenerated/commands/list_custom_llm_models.toml, plugins/connector/permissions/autogenerated/commands/set_custom_llm_model.toml, plugins/connector/permissions/autogenerated/reference.md, plugins/connector/permissions/default.toml, plugins/connector/permissions/schemas/schema.json, plugins/connector/src/commands.rs, plugins/connector/src/ext.rs, plugins/connector/src/lib.rs, plugins/connector/src/store.rs, plugins/local-llm/src/server.rs, plugins/local-stt/src/server.rs, pnpm-lock.yaml
=> Add model params for local-llm

Cargo.toml, packages/utils/src/ai.ts
=> Fix ollama 403 error in release build

apps/desktop/src/components/editor-area/floating-button.tsx
=> Add cancel indicator in enhance button on pending & hover

apps/desktop/src/components/settings/views/extension.tsx, extensions/transcript/src/components/transcript.tsx, extensions/transcript/src/widgets/default/base.tsx
- Removed unnecessary z-index from empty state components in the transcript widget
- Improved session ID handling in the transcript component to use the current session ID if none is provided
- Enhanced the rendering of extension widgets, filtering them based on the selected group
=> Fix transcript widget blur issue

extensions/registry/src/index.ts
Disabled the summary extension by commenting out related code in `extensions/registry/src/index.ts
=> Disable the summary extension

crates/ws/src/client.rs
Previously we only retry for 429 which makes connection request bit unreliable.
=> Better websocket retry

apps/desktop/src/components/settings/views/feedback.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po, apps/desktop/src/routes/app.settings.tsx, apps/docs/data/i18n.json
- Refactor the feedback type options to use more concise and descriptive labels
- Improve the layout and spacing of the feedback form
- Add a textarea for the feedback description with a fixed height
- Improve the email input field styling
- Move the submit button to the bottom of the form
- Use the `useLingui` hook to access the translation functions
=> Improve feedback form UI and functionality

Cargo.lock, apps/app/server/src/native/listen/realtime.rs, crates/detect/src/browser/macos.rs, crates/detect/src/browser/mod.rs, crates/detect/src/lib.rs, crates/stt/src/realtime/mod.rs, plugins/misc/Cargo.toml, plugins/misc/src/ext.rs
=> Reuse Regex in detect crate and parse_meeting_link method

apps/desktop/src/components/left-sidebar/search-list.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po
- Truncate full name and job title in human search results to fit within available space
- Maintain overall layout and readability of search results
=> Improve display of human search results

apps/desktop/src/components/editor-area/note-header/listen-button.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po, apps/docs/data/i18n.json
- Improved the recording consent message for the listen button
- Added internationalization support
=> Improve recording consent message

apps/desktop/src/components/toast/ota.tsx
Removed the mock OTA update functionality from the `OtaNotification` component
=> feat(ota): Remove mock OTA update functionality

apps/desktop/src/components/settings/components/calendar/calendar-selector.tsx
- Sort calendar sources based on criteria: work email domains first, then personal email domains, and calendars without a source last
- Group calendars by their source, and assign calendars without an email domain to the "Other" group
- Improve user experience by making work-related calendars more easily accessible in the calendar selector
=> Improve calendar source sorting/grouping

apps/desktop/src/components/right-panel/views/transcript-view.tsx
Adds a pulsing effect to the live indicator in the transcript view to better highlight the live status. The previous static red dot has been replaced with a pulsing animation to draw more attention to the live state.
=> feat(transcript-view): Enhance live indicator with pulsing effect

apps/desktop/src/components/right-panel/views/transcript-view.tsx
- Added header and body structure to the transcript view component
- Header includes session title, session status, and button to toggle editing mode
- Body includes transcript content, displayed in populated or empty state based on presence of transcript
=> Add header and body structure

apps/desktop/src/components/editor-area/index.tsx
Added analytics to the listen button to track user sessions
=> Analytics for enhancing start

crates/llama/Cargo.toml, crates/whisper/Cargo.toml, plugins/local-stt/Cargo.toml
try to resolve https://github.com/fastrepl/hyprnote/issues/286
Because macos metal support is bad for amd gpu, so it is recommended to disable metal feature,  related issue: https://github.com/ggml-org/llama.cpp/issues/3422
=> fix: try to solve performance issue of macos x86

apps/desktop/src/components/settings/components/ai/llm-view.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po
=> custom llm endpoint model name config fix

apps/desktop/src/components/left-sidebar/notes-list.tsx, apps/desktop/src/components/left-sidebar/search-list.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po
- Disabled auto-scroll functionality in `notes-list.tsx`, `search-list.tsx`, and related components to improve user experience by preventing unexpected page scrolling
- Added i18n support
=> disable-auto-scroll

apps/desktop/src/components/toast/shared.tsx, apps/desktop/src/main.tsx, packages/utils/src/stores/ongoing-session.ts
=> Notification When Recording Fails

crates/db-user/src/events_ops.rs, plugins/apple-calendar/src/sync.rs
=> Fix when Moving Event, Note/Event Becomes Duplicated

apps/desktop/src/components/toast/model-download.tsx
This change adds a dismissible toast notification for model downloads in the desktop application. The toast is displayed when a model download is required, and the user can dismiss the toast to prevent it from showing again during the current session.
The key changes are:
- Add a state variable to track whether the toast has been dismissed
- Check the dismissed state before showing the toast
- Add a "Dismiss" button to the toast that saves the dismissed state in   session storage and dismisses the toast
=> feat(desktop): add dismissible model download toast

apps/desktop/src-tauri/src/ext.rs, apps/desktop/src/components/editor-area/note-header/chips/participants-chip.tsx, apps/desktop/src/components/left-sidebar/top-area/finder-button.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po
-> open contacts view when participant clicked 
-> changed finder view icon
=> Minor fixes UI

apps/desktop/src/components/editor-area/note-header/listen-button.tsx, apps/desktop/src/components/right-panel/views/transcript-view.tsx, apps/desktop/src/locales/en/messages.po, apps/desktop/src/locales/ko/messages.po, crates/whisper-local/src/model.rs, plugins/misc/build.rs, plugins/misc/js/bindings.gen.ts, plugins/misc/permissions/autogenerated/commands/audio_delete.toml, plugins/misc/permissions/autogenerated/reference.md, plugins/misc/permissions/default.toml, plugins/misc/permissions/schemas/schema.json, plugins/misc/src/commands.rs, plugins/misc/src/lib.rs
=> Audio delete support & template selector relocation
