fastrepl/hyprnote

- apps/desktop/src/components/left-sidebar/top-area/settings-button.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- Enhance the design and layout of the settings button dropdown menu
- Introduce a new header section with a gradient background, CPU icon, and "Local mode" label
- Adjust the overall width of the dropdown menu to 52 pixels
- Add a subtle background pattern to the header section
- Adjust the spacing and alignment of the settings and profile menu items
- Remove the "DropdownMenuLabel" and "DropdownMenuSeparator" components
> Redesigned Settings Dropdown with New Local Mode Header and Improved Layout

- apps/desktop/src/components/left-sidebar/events-list.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
This commit adds a context menu to the event items in the events list, providing
users with additional options to interact with the events. The main changes
include:
1. Implement a context menu using the `ContextMenu` component from the `@hypr/ui`
library.
2. Add two context menu items:
- "New window": Opens the associated session in a new window.
- "View in calendar": Navigates to the calendar view with the event's date
pre-selected.
3. Refactor the `EventItem` component to handle the context menu and the new
navigation options.
4. Improve the formatting and readability of the code.
> feat(events-list): Add context menu and navigation options

- crates/db-user/src/init.rs
Removes the unused `calendar_event_id` field from the `Session` struct
and removes the unnecessary `id` field from the `Session` creation in
the `seed` function. These changes simplify the `Session` struct and
the session creation process.
> feat(user-db): Remove unused calendar event ID from session

- apps/desktop/src/components/left-sidebar/events-list.tsx
- apps/desktop/src/components/left-sidebar/notes-list.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- Implement a pending state indicator (splash loader) for event and note items in the left sidebar
- Update localization strings for note deletion confirmation and "New window" button
> Add Pending State Indicator for Sidebar Items and Update Localization Strings

- apps/desktop/src/components/editor-area/note-header/listen-button.tsx
- Disable the button and set the opacity to 10% when the session is in the "enhance pending" state
- Add a box-shadow to the button to create a subtle border effect
- Refactor the button styles to use Tailwind CSS utility classes instead of inline styles
> Refactor Button Styles and Add Enhance-Pending State UI Feedback

- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- extensions/transcript/src/components/transcript.tsx
- extensions/transcript/src/hooks/useTranscript.ts
- Add support for using the current session ID if none is provided in the `TranscriptProps`
- Improve the handling of the ongoing session state in the `useTranscript` hook
- Separate the ongoing session status and session ID into a single state object
- Only show the "LIVE" indicator if the current session is the one being recorded
- Add a loading state to the hook to indicate when the timeline data is being fetched
- Unsubscribe from live updates when the current session is not the ongoing session
- Update the text strings used in the listen button component across the English and Korean locales
> Improve Transcript Hook Logic and Session Handling with Updated Listen Button Texts

- extensions/transcript/src/hooks/useTranscriptWidget.ts
- extensions/transcript/src/widgets/default/2x2.tsx
- extensions/transcript/src/widgets/default/full.tsx
- Add a new `isEnhanced` flag to the `useTranscriptWidget` hook to check if the current session has an enhanced memo HTML.
- Update the empty state message to display "No transcript available" if the session is enhanced, and "Meeting is not active" if the session is not enhanced.
- Add the `isLoading` flag to the `useTranscriptWidget` hook to prevent the empty state message from being displayed while the transcript is still loading.
> feat(transcript): enhance empty state message

- apps/desktop/src-tauri/tauri.conf.json
Reduce the window height from 438 to 400 pixels to provide a more compact and user-friendly interface for the desktop application. This change ensures the application window fits better on various screen sizes and improves the overall user experience.
> feat(desktop): Adjust DMG window size

- apps/desktop/src/components/toolbar/bars/default-toolbar.tsx
- apps/desktop/src/components/toolbar/bars/index.tsx
- apps/desktop/src/components/toolbar/index.tsx
- Added a new `DefaultToolbar` component that can be used in place of the `TransparentToolbar` component
- The `DefaultToolbar` component includes an optional `title` prop to display a title within the toolbar
- Updated the `Toolbar` component to use the `DefaultToolbar` component when the current route matches the "Plans" route
> Introduce DefaultToolbar Component and Integrate with Plans Route

- extensions/timer/src/widgets/analog/2x2.tsx
- extensions/timer/src/widgets/digital/2x1.tsx
- Adds click-outside handling for the timer editing mode
- Improves the user experience by providing a more intuitive way to exit the editing mode without having to manually click the "Done" button
> Add click-outside behavior to exit timer editing mode for improved UX

- apps/desktop/src/routes/app.plans.tsx
Added a `source=APP` parameter to the pro waitlist link to track where the user came from
> Add source parameter to pro waitlist link

- .cargo/config.toml
- fix: macOS builds, these are currently broken due a hardcoded requirement for a MS Windows compiler flag (`/MT`)
> fix(build): fix broken builds on macOS due to hardcoded windows var

- apps/desktop/src/components/left-sidebar/top-area/settings-button.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- Added the app version to the settings menu
- The version is fetched using the `getVersion` function from the `@tauri-apps/api/app` module
- The version is displayed in a disabled dropdown menu item
- This change provides users with easy access to the current version of the application, which can be useful for troubleshooting or checking for updates
> Add app version to settings menu

- CONTRIBUTING.md
Executing `pnpm install && turbo -F @hypr/desktop tauri:dev` ran into issues on my M1 Mac machine. This was caused by `whisper-rs`. I found that the solution is to install `cmake`. 
Added `brew install cmake` to the `Setup` -> `Requirements` section of `CONTRIBUTING.md`
See issue [failed to run custom build command for `whisper-rs-sys v0.12.1 (https://github.com/tazz4843/whisper-rs(...)](#297) for more information
> Updated Setup -> Requirements section. Added dependency on cmake

- extensions/twenty/src/widgets/default/2x2.tsx
- extensions/twenty/src/widgets/hooks/useTwentyNotes.ts
- Passes the `queryClient` as a parameter to the `useTwentyNotes` hook
- Updates the `useMutation` and `useQuery` calls in the `useTwentyNotes` hook to use the provided `queryClient`
- Adds a fallback UI in the `2x2.tsx` file to display an error message when the `queryClient` is not provided
These changes ensure that the `useTwentyNotes` hook can properly interact with the React Query cache, improving the overall performance and reliability of the Twenty widget.
> Add queryClient to useTwentyNotes hook

- apps/desktop/src/components/settings/views/extension.tsx
- apps/desktop/src/routes/app.note.$id.tsx
- Optimized the window layout for the video and main views in the desktop application
- Removed the explicit positioning of the video and main windows, allowing the default window resizing to handle the layout automatically
- Ensured the main window is resized to its default size after the video window is shown
> Remove window positioning

- plugins/windows/src/ext.rs
- Center windows on the screen instead of positioning them relative to the cursor
- Provide a more consistent user experience and ensure that the windows are always visible and accessible
- Update the `HyprWindow` implementation in `plugins/windows/src/ext.rs` to use the `window.center()` method instead of manually calculating the position based on the cursor coordinates
> Center windows on screen

- apps/desktop/src/components/editor-area/note-header/listen-button.tsx
- apps/desktop/src/components/editor-area/note-header/shiny-button.tsx
- Added a `disabled` prop to the `ShinyButton` component, allowing the button to be disabled when necessary (e.g., during a process)
- Added an analytics event to track when the user starts the onboarding video session, including the `userId` and `sessionId` as event properties
> Track onboarding video start event with analytics

- apps/desktop/src/contexts/right-panel.tsx
- Added a new flag to check if the chat panel is enabled
- The flag is used to conditionally enable the hotkey for toggling the right panel
- This ensures the hotkey is only active when the chat panel is enabled, improving the user experience
> Disable chat shortcut if feature flag is disabled

- apps/desktop/src/components/editor-area/note-header/chips/event-chip.tsx
- apps/desktop/src/components/editor-area/note-header/chips/participants-chip/index.tsx
- apps/desktop/src/components/editor-area/note-header/chips/participants-chip/participants-list.tsx
- Increase the width of the participants popover to 80% to accommodate longer participant names.
- Add opacity and cursor styles to the event chip when there is no event data or the current session is the onboarding session.
- Increase the width of the event popover to 72 to better display the event details.
- Limit the maximum height of the participants list to 40vh and add a custom scrollbar for better readability.
> Improve participants and event chips

- crates/db-user/src/init.rs
Renamed the onboarding note and session to "Welcome to Hyprnote" to better reflect the purpose of the onboarding process for new users.
> Rename onboarding to "Welcome to Hyprnote"

- apps/desktop/src/components/settings/views/extension.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- apps/desktop/src/routes/video.tsx
- plugins/windows/src/events.rs
- Simplified video player handling by removing unnecessary logic to expand the left sidebar and collapse the right panel when the video ends
- Updated the logic to expand the right panel when the video reaches a certain timestamp
- Adjusted the main window state when the extension view is loaded, collapsing the left sidebar by default and expanding the right panel
> Prevent left sidebar from opening up after closing Settings view

- apps/desktop/src/routes/app.organization.$id.tsx
- apps/desktop/src/utils/url-parser.ts
- Add support for parsing URLs in text
- Introduce a new utility function `parseUrlsToLinks` that converts URLs in a string of text to clickable links
- Use a regular expression to identify URLs in the text and wrap them in `<a>` tags with appropriate `href` and `target` attributes
- Handle line breaks in the input text, ensuring the resulting React nodes are properly structured with `<br>` elements
> Add support for parsing URLs in text

- apps/desktop/src/components/left-sidebar/notes-list.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- packages/utils/src/datetime.ts
- Used `created_at` for session grouping in the notes list
- Improved date formatting for past and future dates
- Displays time in "h:mm a" format for same-day dates
- Uses `formatUpcomingTime` for future dates
- Uses `formatTimeAgo` for past dates
- Updated `formatRelative` function to handle future dates (less than 7 days from now) and display the number of days until the date
> Fixed left sidebar grouping

- packages/tiptap/src/shared/custom-list-keymap.ts
- packages/tiptap/src/shared/extensions.ts
- Added a custom list keymap that extends the default list keymap provided by the Tiptap library
- The custom keymap handles the Enter and Backspace keys to provide a better user experience when working with list items
- The Enter key now lifts the list item if the current list item is empty, allowing the user to easily exit the list
- The Backspace key also lifts the list item if the current list item is empty and the cursor is at the beginning of the list item, allowing the user to easily remove the list item
- Replaced the `ListKeymap` extension with the new `CustomListKeymap` extension, providing more fine-grained control over the behavior of list items
> Enhance List Editing UX with Custom Tiptap List Keymap for Enter and Backspace Handling

- apps/desktop/src/components/settings/views/lab.tsx
- Removed the `ChatPanel` component from the Lab settings view
- The `ChatPanel` component was responsible for displaying a feature flag to enable or disable the "Hyprnote Assistant" functionality
- The removal of this component is likely due to a decision to no longer include this feature in the current release or to move it to a different location within the application
> feat: Remove ChatPanel component from Lab settings view

- apps/desktop/src/components/right-panel/views/transcript-view.tsx
- Added a new "Start recording" button to the transcript view, which allows the user to start a recording session
- Implemented an empty state UI, which is displayed when there is no active session or when the transcript is not available
- Conditionally rendered the transcript content or the empty state based on the session ID and the status of the ongoing session
> Add start recording button and empty state

- apps/desktop/src/components/editor-area/note-header/listen-button.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- apps/docs/data/i18n.json
- packages/utils/src/stores/ongoing-session.ts
- Improved audio controls and consent handling in the `ListenButton` component
- Added a new `CheckIcon` to indicate the current state of the audio controls
- Handled the case where the user closes the popover without giving consent, preventing the consent screen from showing again automatically
- Ensured the speaker is muted by default when the recording starts, if the consent screen is shown
- Tracked the initial mount state to handle the speaker mute logic correctly
> Enhance Audio Consent UX and Speaker Controls in ListenButton Component

- apps/desktop/src/components/right-panel/views/transcript-view.tsx
- Adjusted the size of the recording indicator in the transcript view
- Removed an unnecessary margin-right to make the indicator more compact
- Improved the overall layout and visual consistency of the transcript view
> Adjust recording indicator size

- apps/desktop/src/components/right-panel/views/transcript-view.tsx
- Replaced `ClipboardCopyIcon` and `FileAudioIcon` with `Copy` and `AudioLinesIcon` to improve visual consistency and clarity
- Added a new button to allow users to copy the entire transcript, enhancing the overall functionality of the feature
> Replace icons and add copy functionality

- apps/desktop/src/components/right-panel/views/transcript-view.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- apps/docs/data/i18n.json
- Removes the ellipses (three or more periods) from the transcript text when copying the full transcript
- Ensures a cleaner and more readable text is copied to the clipboard
> fix transcript copy-all

- apps/desktop/src/components/right-panel/index.tsx
Increases the minimum size of the right panel from 0 to 30 pixels. This change ensures that the right panel is always visible and provides a better user experience when the panel is resized.
> feat(right-panel): increase minimum size of right panel

- apps/desktop/src/components/editor-area/note-header/chips/event-chip.tsx
- Added a tooltip to the event chip in the note header to display the full date and time of the event
- This provides more detailed information to the user without cluttering the UI
> Add tooltip to event chip

- apps/desktop/src/components/settings/components/ai/stt-view.tsx
- apps/desktop/src/components/welcome-modal/index.tsx
- apps/desktop/src/components/welcome-modal/model-selection-view.tsx
- apps/desktop/src/components/welcome-modal/rating-display.tsx
- apps/desktop/src/components/welcome-modal/welcome-view.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- apps/desktop/src/routes/app.tsx
- apps/docs/data/i18n.json
- Added a new `ModelSelectionView` component that allows the user to select a supported STT model
- Integrated the `ModelSelectionView` into the `WelcomeModal`, providing a seamless transition between the welcome screen and the model selection
- Implemented the logic to set the current STT model using the `localSttCommands.setCurrentModel` mutation
- Improved the overall layout and styling of the `WelcomeModal` to provide a more polished and visually appealing experience
- Refactored the `WelcomeModal` to handle the state and logic for toggling between the welcome view and the model selection view
- Introduced the new `WelcomeModal` component and removed the `LoginModal` component to improve the onboarding process for new users
> Welcome modal

- apps/docs/development/mac-arm-build-issues.md
This PR adds a documentation page that outlines three issues encountered when building Hyprnote on Apple Silicon (Mac ARM):
1. Intel Homebrew/CMake conflict
2. dotprod-related build error
3. Rust/CMake optimization mismatch
Each issue includes detailed error messages, solutions, and verification results.
Hope this helps other contributors working on ARM-based macOS systems.
> docs: add Mac ARM build troubleshooting guide

- apps/desktop/src/components/editor-area/note-header/chips/event-chip.tsx
- apps/desktop/src/components/left-sidebar/notes-list.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
> Fix Event Assignment to New Note

- apps/desktop/src/components/left-sidebar/index.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- apps/docs/data/i18n.json
- Improved event and note filtering logic in the left sidebar
- Events now only show future events not part of the ongoing or active session
- Notes now only show sessions without any future events associated with them
- Ensures the left sidebar displays the most relevant information to the user
> improve-event-and-note-filtering

- apps/desktop/src/components/right-panel/views/transcript-view.tsx
- apps/desktop/src/locales/en/messages.po
- apps/desktop/src/locales/ko/messages.po
- packages/tiptap/src/transcript/index.tsx
This commit introduces several improvements to the transcript component:
- Adds padding-bottom to the scroll container to ensure content is not hidden behind the footer
- Increases the minimum height of the EditorContent component to prevent content from being cut off
- Removes the search icon button from the transcript view, as it was not being used
- Simplifies the logic for determining the layout based on the panel width, making it more concise and easier to understand
These changes aim to enhance the user experience by improving the visual presentation and functionality of the transcript component.
> feat(transcript): improve scrolling and layout

- apps/desktop/src/components/left-sidebar/index.tsx
The changes in this commit focus on improving the event fetching and display logic in the left sidebar component:
1. The `queryKey` for the events query is updated to include the `activeSessionId` in addition to the `ongoingSessionId`. This ensures that the query is invalidated when the active session changes.
2. The events are now fetched for a 60-day range starting from the current date, instead of the previous 12-hour range. This allows the component to display upcoming events more accurately.
3. The fetched events are filtered to only include upcoming events, sorted by start date, and the first 3 events are displayed. This ensures that the user sees the most relevant upcoming events.
4. If the active session is not already in the list of events to be displayed, it is added to the list …
> feat(left-sidebar): Fetch upcoming events and handle active session

- Cargo.lock
- Cargo.toml
- apps/app/server/src/native/listen/realtime.rs
- crates/audio-utils/src/lib.rs
- crates/stt/src/realtime/clova.rs
- crates/stt/src/realtime/deepgram.rs
- crates/stt/src/realtime/whisper.rs
- crates/whisper-cloud/src/client.rs
- crates/whisper-local/src/model.rs
- crates/whisper-local/src/stream.rs
- crates/ws-utils/Cargo.toml
- crates/ws-utils/src/lib.rs
- crates/ws/src/client.rs
- plugins/listener-interface/Cargo.toml
- plugins/listener-interface/src/lib.rs
- plugins/listener/Cargo.toml
- plugins/listener/src/client.rs
- plugins/listener/src/fsm.rs
- plugins/local-stt/src/server.rs
> Implement binary diarization

- apps/desktop/src/components/left-sidebar/top-area/settings-button.tsx
The changes update the link in the settings button to point to the
"Talk to Founders" page on the Cal.com website. This change is
intended to provide users with a more direct way to contact the
Hyprnote team.
> feat(left-sidebar): update settings button link

- apps/desktop/src/components/left-sidebar/top-area/settings-button.tsx
The changelog URL in the settings button is updated from
"https://hyprnote.canny.io/changelog" to "https://hyprnote.com/changelog".
This change ensures that the correct URL is used to access the
application's changelog.
> Changed URL in changelog button
